# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba9b8b952f86e1d2d1bf816d041a0c2e73a2c5fcc64f4accdd86e473c47f8659325f57ebf755020faa2b263905442bc08de4d64051c41862ef56f9d8f9f65990

test:
  secret_key_base: fd339a8f797398423c64d14ede0d5eba5c57d485a044fe151f2851cb80d018ccdc0916cbe6cb6aef9499cd8247e66b193a533c7506ad178dd79e7b68c81886bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
